version: "3"
services:
  app:
    #build: .
    build:
      context: ./main
      dockerfile: Dockerfile    
    container_name: my-hello-world-api2
    command: nodemon server.js --verbose
    ports:
      - 3008:3008
    volumes:
      #- .:/app
      - ./main:/app      
    depends_on:
      - db

  db:
    image: mongo
    container_name: mongodb2
    ports:
      - 27017:27017

  postgres_db:
    image: postgres:latest
    container_name: postgresql_container
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: MAKAKA
      POSTGRES_USER: makar
      POSTGRES_PASSWORD: ua
    ports:
      - "5432:5432"      

  mongo-express:
    image: mongo-express
    container_name: mongo-express2
    ports:
      - 8081:8081
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
    depends_on:
      - db
